name: Run Playwright Tests (Azure Repo)

on:
  workflow_dispatch:   # allows manual run
    inputs:
      branch:
        description: 'Branch from Azure'
        required: true
        default: 'main'
      testFile:
        description: 'Test file to run'
        required: true
        default: 'tests/example.spec.js'

jobs:
  playwright-test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Azure Repo
        run: |
          git clone --branch ${{ github.event.inputs.branch }} https://AnytimeCollect:${{ secrets.AZURE_PAT }}@dev.azure.com/AnytimeCollect/Lockstep/_git/TestCases-ReactATC azure-repo
        env:
          GIT_ASKPASS: /bin/echo
          GIT_USERNAME: Lockstep   # usually your Azure DevOps org name
          GIT_PASSWORD: ${{ secrets.AZURE_PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd azure-repo
          npm ci

      - name: Run Playwright Tests
        run: |
          cd azure-repo
          npx playwright test ${{ github.event.inputs.testFile }} --reporter=html --output=playwright-report

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: azure-repo/playwright-report
