name: Run Playwright Tests (Azure Repo)

on:
  workflow_dispatch:   # allows manual run
    inputs:
      branch:
        description: 'Branch from Azure'
        required: true
        default: 'main'
      testFile:
        description: 'Test file to run'
        required: true
        default: 'tests/example.spec.js'
      environment:     # 👈 dropdown/input field when triggering
        description: "Environment to run tests against"
        required: true
        default: "qa"
      workers:
        description: 'Number of workers'
        required: false
        default: '4'  

jobs:
  playwright-test:
    name: Run Tests – ${{ steps.sanitize.outputs.filename }}
    runs-on: ubuntu-latest

    steps:
      - name: Clone Azure Repo
        run: |
          git clone --branch ${{ github.event.inputs.branch }} https://AnytimeCollect:${{ secrets.AZURE_PAT }}@dev.azure.com/AnytimeCollect/Lockstep/_git/TestCases-ReactATC azure-repo
        env:
          GIT_ASKPASS: /bin/echo
          GIT_USERNAME: Lockstep   # usually your Azure DevOps org name
          GIT_PASSWORD: ${{ secrets.AZURE_PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd azure-repo
          npm install

      - name: Install Playwright Browsers
        run: |
          cd azure-repo
          npx playwright install --with-deps    

      - name: Run Playwright Tests
        run: |
          cd azure-repo
          echo "::group::Running Playwright Tests"
          npx cross-env ENVIRONMENT=${{ github.event.inputs.environment }} playwright test tests/Admin_MasterFiles_ActivityType.spec.js --reporter=list,html --output=playwright-report --workers=${{ github.event.inputs.workers }} --verbose
          echo "::endgroup::"
          
      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ github.event.inputs.testFile }}
          path: azure-repo/playwright-report
