name: Run Playwright Tests from Azure Repo

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch from Azure DevOps'
        required: true
        default: 'main'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout this GitHub repo (workflow lives here, no Azure code copied)
      - name: Checkout GitHub Repo
        uses: actions/checkout@v3

      # 2. Clone the Azure DevOps repo (temporary in runner VM)
      - name: Clone Azure Repo
        run: |
          git clone --branch ${{ github.event.inputs.branch }} https://dev.azure.com/AnytimeCollect/Lockstep/_git/TestCases-ReactATC azure-repo
        env:
          GIT_ASKPASS: /bin/echo
          GIT_USERNAME: Lockstep
          GIT_PASSWORD: ${{ secrets.AZURE_PAT }}

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          cd azure-repo
          npm ci

      # 4. Run Playwright tests with HTML report
      - name: Run Playwright Tests
        run: |
          cd azure-repo
          npx playwright test --reporter=html --output=playwright-report

      # 5. Upload report as artifact (downloadable)
      - name: Upload Playwright Report
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: azure-repo/playwright-report
